# Generated by Django 5.2.17 on 2026-09-06 17:25

import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("document_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("ocr", "Ocr"), ("delete_object", "Delete")], max_length=16
                    ),
                ),
                ("storage_key", models.CharField(blank=True, max_length=512)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("run_token", models.UUIDField(blank=True, null=True)),
                ("request_id", models.UUIDField(default=uuid.uuid4)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["state", "available_at"], name="job_dispatch_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("document_id", models.UUIDField(db_index=True)),
                ("actor_kind", models.CharField(default="user", max_length=16)),
                ("action", models.CharField(max_length=32)),
                ("request_id", models.UUIDField(default=uuid.uuid4)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["owner", "-created_at"], name="audit_owner_created_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("storage_key", models.CharField(editable=False, max_length=512, unique=True)),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=64)),
                ("size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("document_type", models.CharField(blank=True, default="", max_length=64)),
                ("tags", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True, default="")),
                ("processing_info", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.CharField(blank=True, default="", max_length=255)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, editable=False, max_length=128, null=True),
                ),
                (
                    "request_fingerprint",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("search_text", models.TextField(default="", editable=False)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at", "-id"], name="doc_owner_created_idx"
                    ),
                    models.Index(fields=["status", "created_at"], name="doc_status_created_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="doc_search_gin"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("owner", "idempotency_key"),
                        name="unique_owner_upload_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("size__gt", 0)), name="document_size_positive"
                    ),
                ],
            },
        ),
    ]
